/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/templates/createImage": {
    /** @description Create an image from a template */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * @default png
             * @enum {string}
             */
            format?: "png" | "jpeg" | "webp"
            /** @description Only for debug purpose, it draws bounding box for each layer */
            _debug?: boolean | string
            /** @description Optional custom S3 configuration. If provided, the generated file will be stored in your S3-compatible storage instead of the default Bannerify storage. */
            s3Config?: {
              /**
               * @description S3 endpoint URL (without protocol)
               * @example s3.amazonaws.com
               */
              endPoint: string
              /**
               * @description S3 endpoint port
               * @default 443
               * @example 443
               */
              port?: number
              /**
               * @description Whether to use SSL/TLS
               * @default true
               * @example true
               */
              useSSL?: boolean
              /**
               * @description S3 region
               * @example us-east-1
               */
              region: string
              /**
               * @description S3 bucket name
               * @example my-images-bucket
               */
              bucket: string
              /**
               * @description Whether to use path-style URLs
               * @default false
               * @example false
               */
              pathStyle?: boolean
              /** @description S3 access key */
              accessKey: string
              /** @description S3 secret key */
              secretKey: string
              /**
               * @description Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
               * @example https://cdn.example.com/{key}
               */
              customUrl?: string
            }
            apiKey: string
            /**
             * @description Your template id
             * @example tpl_xxxxxxxxx
             */
            templateId: string
            /**
             * @description Template modifications as the API array format, an object shorthand, or a JSON string. Object values map to text by default, while nested objects keep fields such as src, qrcode, rows, or columns.
             * @default []
             * @example {
             *   "headline": "Summer sale",
             *   "photo": {
             *     "src": "https://example.com/photo.png"
             *   }
             * }
             */
            modifications?: unknown
            /**
             * @description Generate thumbnail preview (non-billable)
             * @default false
             */
            thumbnail?: boolean | string
          }
        }
      }
      responses: {
        /** @description A image file */
        200: {
          content: {
            "image/png": string
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/templates/createPdf": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            apiKey: string
            /**
             * @description Your template ID
             * @example tpl_xxx
             */
            templateId: string
            /**
             * @description Template modifications as the API array format, an object shorthand, or a JSON string. Object values map to text by default, while nested objects keep fields such as src, qrcode, rows, or columns.
             * @default []
             * @example {
             *   "headline": "Summer sale",
             *   "photo": {
             *     "src": "https://example.com/photo.png"
             *   }
             * }
             */
            modifications?: unknown
          }
        }
      }
      responses: {
        /** @description Success create pdf */
        200: {
          content: {
            "application/pdf": string
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/templates/signedurl": {
    /** @description Generate a signed URL for a template */
    get: {
      parameters: {
        query: {
          format?: "png" | "jpeg" | "webp"
          /** @description By default, we cache the image in the CDN for 1 day to save your bandwidth, use this field to disable cache so you can get the latest image */
          nocache?: boolean | string
          /** @description Only for debug purpose, it draws bounding box for each layer */
          _debug?: boolean | string
          /** @description Optional custom S3 configuration. If provided, the generated file will be stored in your S3-compatible storage instead of the default Bannerify storage. */
          s3Config?: {
            /**
             * @description S3 endpoint URL (without protocol)
             * @example s3.amazonaws.com
             */
            endPoint: string
            /**
             * @description S3 endpoint port
             * @default 443
             * @example 443
             */
            port?: number
            /**
             * @description Whether to use SSL/TLS
             * @default true
             * @example true
             */
            useSSL?: boolean
            /**
             * @description S3 region
             * @example us-east-1
             */
            region: string
            /**
             * @description S3 bucket name
             * @example my-images-bucket
             */
            bucket: string
            /**
             * @description Whether to use path-style URLs
             * @default false
             * @example false
             */
            pathStyle?: boolean
            /** @description S3 access key */
            accessKey: string
            /** @description S3 secret key */
            secretKey: string
            /**
             * @description Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
             * @example https://cdn.example.com/{key}
             */
            customUrl?: string
          }
          /** @description Your template id */
          templateId: string
          /** @description Deprecated alias of apiKeyHashed */
          apiKeyMd5?: string
          /** @description SHA-256 hash of the API key, it identifies which key signed the URL */
          apiKeyHashed?: string
          /** @description HMAC-SHA256 of the sorted query params, keyed with the API key, read more at https://bannerify.co/docs/api-reference/endpoint/signed-url */
          sign: string
          /** @description Template modifications as the API array format, an object shorthand, or a JSON string. Object values map to text by default, while nested objects keep fields such as src, qrcode, rows, or columns. */
          modifications?: unknown
          /** @description Generate thumbnail preview (low-quality, non-billable) */
          thumbnail?: boolean | string
        }
      }
      responses: {
        /** @description A image file */
        200: {
          content: {
            "image/png": string
            "image/jpeg": string
            "image/webp": string
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/info": {
    /** @description Get project info */
    get: {
      parameters: {
        query: {
          /** @description The api key to use for this request */
          apiKey: string
        }
      }
      responses: {
        /** @description Project info */
        200: {
          content: {
            "application/json": {
              id: string
              name: string
              createdAt: string
            }
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/templates": {
    /** @description List templates */
    get: {
      parameters: {
        query: {
          /** @description The api key to use for this request */
          apiKey: string
          /** @description Whether to include layers in the response */
          includeLayers?: boolean | string
        }
      }
      responses: {
        /** @description A list of templates */
        200: {
          content: {
            "application/json": unknown[]
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/templates/:id": {
    /** @description Template details */
    get: {
      parameters: {
        query: {
          /** @description The api key to use for this request */
          apiKey: string
        }
      }
      responses: {
        /** @description Template details */
        200: {
          content: {
            "application/json": {
              /** @description The name of the template */
              name: string
              /** @description The id of the template */
              id: string
              /** @description The layers of the template */
              layers: {
                /** @description The name of the layer */
                name: string
                /** @description The id of the layer */
                id: string
                /** @description The type of the layer */
                type: string
                /** @description The suggest input of the layer */
                suggestInput: string | null
              }[]
            }
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/templates/createStoredImage": {
    /** @description Create an image from a template */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * @default png
             * @enum {string}
             */
            format?: "png" | "jpeg" | "webp"
            /** @description Only for debug purpose, it draws bounding box for each layer */
            _debug?: boolean | string
            /** @description Optional custom S3 configuration. If provided, the generated file will be stored in your S3-compatible storage instead of the default Bannerify storage. */
            s3Config?: {
              /**
               * @description S3 endpoint URL (without protocol)
               * @example s3.amazonaws.com
               */
              endPoint: string
              /**
               * @description S3 endpoint port
               * @default 443
               * @example 443
               */
              port?: number
              /**
               * @description Whether to use SSL/TLS
               * @default true
               * @example true
               */
              useSSL?: boolean
              /**
               * @description S3 region
               * @example us-east-1
               */
              region: string
              /**
               * @description S3 bucket name
               * @example my-images-bucket
               */
              bucket: string
              /**
               * @description Whether to use path-style URLs
               * @default false
               * @example false
               */
              pathStyle?: boolean
              /** @description S3 access key */
              accessKey: string
              /** @description S3 secret key */
              secretKey: string
              /**
               * @description Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
               * @example https://cdn.example.com/{key}
               */
              customUrl?: string
            }
            apiKey: string
            /**
             * @description Your template id
             * @example tpl_xxxxxxxxx
             */
            templateId: string
            /**
             * @description Template modifications as the API array format, an object shorthand, or a JSON string. Object values map to text by default, while nested objects keep fields such as src, qrcode, rows, or columns.
             * @default []
             * @example {
             *   "headline": "Summer sale",
             *   "photo": {
             *     "src": "https://example.com/photo.png"
             *   }
             * }
             */
            modifications?: unknown
          }
        }
      }
      responses: {
        /** @description Image object */
        200: {
          content: {
            "application/json": {
              url: string
            }
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
  "/v1/templates/createStoredPdf": {
    /** @description Create a PDF from a template and store it in Bannerify storage */
    post: {
      requestBody: {
        content: {
          "application/json": {
            apiKey: string
            /**
             * @description Your template id
             * @example tpl_xxxxxxxxx
             */
            templateId: string
            /**
             * @description Template modifications as the API array format, an object shorthand, or a JSON string. Object values map to text by default, while nested objects keep fields such as src, qrcode, rows, or columns.
             * @default []
             * @example {
             *   "headline": "Summer sale",
             *   "photo": {
             *     "src": "https://example.com/photo.png"
             *   }
             * }
             */
            modifications?: unknown
            /** @description Custom S3 configuration for storing generated files in your own S3-compatible storage */
            s3Config?: {
              /**
               * @description S3 endpoint URL (without protocol)
               * @example s3.amazonaws.com
               */
              endPoint: string
              /**
               * @description S3 endpoint port
               * @default 443
               * @example 443
               */
              port?: number
              /**
               * @description Whether to use SSL/TLS
               * @default true
               * @example true
               */
              useSSL?: boolean
              /**
               * @description S3 region
               * @example us-east-1
               */
              region: string
              /**
               * @description S3 bucket name
               * @example my-images-bucket
               */
              bucket: string
              /**
               * @description Whether to use path-style URLs
               * @default false
               * @example false
               */
              pathStyle?: boolean
              /** @description S3 access key */
              accessKey: string
              /** @description S3 secret key */
              secretKey: string
              /**
               * @description Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
               * @example https://cdn.example.com/{key}
               */
              customUrl?: string
            }
          }
        }
      }
      responses: {
        /** @description Stored PDF object */
        200: {
          content: {
            "application/json": {
              /** @description Public URL of the generated PDF */
              url: string
            }
          }
        }
        /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
        400: {
          content: {
            "application/json":
              | components["schemas"]["ErrBadRequest"]
              | components["schemas"]["ErrFetchImageError"]
          }
        }
        /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
        401: {
          content: {
            "application/json": components["schemas"]["ErrUnauthorized"]
          }
        }
        /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
        403: {
          content: {
            "application/json": components["schemas"]["ErrForbidden"]
          }
        }
        /** @description The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web. */
        404: {
          content: {
            "application/json": components["schemas"]["ErrNotFound"]
          }
        }
        /** @description This response is sent when a request conflicts with the current state of the server. */
        409: {
          content: {
            "application/json": components["schemas"]["ErrConflict"]
          }
        }
        /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
        429: {
          content: {
            "application/json": components["schemas"]["ErrTooManyRequests"]
          }
        }
        /** @description The server has encountered a situation it does not know how to handle. */
        500: {
          content: {
            "application/json": components["schemas"]["ErrInternalServerError"]
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    ErrBadRequest: {
      error: {
        /**
         * @description A machine readable error code.
         * @example BAD_REQUEST
         * @enum {string}
         */
        code: "BAD_REQUEST"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/BAD_REQUEST
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrFetchImageError: {
      error: {
        /**
         * @description A machine readable error code.
         * @example FETCH_IMAGE_ERROR
         * @enum {string}
         */
        code: "FETCH_IMAGE_ERROR"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/FETCH_IMAGE_ERROR
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrUnauthorized: {
      error: {
        /**
         * @description A machine readable error code.
         * @example UNAUTHORIZED
         * @enum {string}
         */
        code: "UNAUTHORIZED"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/UNAUTHORIZED
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrForbidden: {
      error: {
        /**
         * @description A machine readable error code.
         * @example FORBIDDEN
         * @enum {string}
         */
        code: "FORBIDDEN"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/FORBIDDEN
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrNotFound: {
      error: {
        /**
         * @description A machine readable error code.
         * @example NOT_FOUND
         * @enum {string}
         */
        code: "NOT_FOUND"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/NOT_FOUND
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrConflict: {
      error: {
        /**
         * @description A machine readable error code.
         * @example CONFLICT
         * @enum {string}
         */
        code: "CONFLICT"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/CONFLICT
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrTooManyRequests: {
      error: {
        /**
         * @description A machine readable error code.
         * @example TOO_MANY_REQUESTS
         * @enum {string}
         */
        code: "TOO_MANY_REQUESTS"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/TOO_MANY_REQUESTS
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    ErrInternalServerError: {
      error: {
        /**
         * @description A machine readable error code.
         * @example INTERNAL_SERVER_ERROR
         * @enum {string}
         */
        code: "INTERNAL_SERVER_ERROR"
        /**
         * @description A link to our documentation with more details about this error code
         * @example https://bannerify.co/docs/api-reference/errors/code/INTERNAL_SERVER_ERROR
         */
        docs: string
        /** @description A human readable explanation of what went wrong */
        message: string
        /**
         * @description Please always include the requestId in your error report
         * @example req:1234
         */
        requestId: string
      }
    }
    /** @description A modification (aka override) to apply to the layer in image */
    Modification: {
      /**
       * @description The layer name of the modification
       * @example Text 1
       */
      name: string
      /**
       * @description The color for the modification
       * @example #FF0000
       */
      color?: string
      /**
       * @description The source image for the modification
       * @example https://example.com/image.jpg
       */
      src?: string
      /**
       * @description You can modify the text layer with this field
       * @example Hello World
       */
      text?: string
      /**
       * @description Modify the barcode layer content with this field
       * @example 1234567890
       */
      barcode?: string
      /**
       * @description Modify the qrcode layer content with this field
       * @example Some text
       */
      qrcode?: string
      /**
       * @description Set the visibility of the field
       * @example true
       */
      visible?: boolean
      /**
       * @description Star value
       * @example 5
       */
      star?: number
      /**
       * @description The rows of a data layer. A table takes row objects keyed by the column names, a chart takes { label, value } points, and a key value layer takes { key, value } entries.
       * @example [
       *   {
       *     "label": "Jan",
       *     "value": 22
       *   }
       * ]
       */
      rows?: unknown[]
      /**
       * @description The column names of a table layer
       * @example [
       *   "Item",
       *   "Qty",
       *   "Total"
       * ]
       */
      columns?: string[]
      /**
       * @description The heading of an alert layer, or the job title of a signature layer
       * @example Payment terms
       */
      title?: string
      /**
       * @description The date of a signature layer
       * @example 2026-01-31
       */
      date?: string
    }
  }
  responses: never
  parameters: {}
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export type operations = Record<string, never>
